In [2]:
import pickle
import pandas as pd
from faker import Faker
import random

In [2]:
#open pkl file
with open('movies.pkl', 'rb') as f:
    data = pickle.load(f)

In [5]:
pd.set_option('display.max_colwidth', None) # Display full contents of cells

In [4]:
#converting the data to datafram
df = pd.DataFrame(data)

In [5]:
# copying the dataset
df_movies_clean = df.copy()

# deleting the column
df_movies_clean.drop(['category'], axis=1, inplace=True)

# heading
df_movies_clean.head()

,title,description,type,tags,image,duration,uploaddate,warning,rating
0,The Soul of Flies,"A tale of two brothers who meet for the first time on the way to their father's funeral, who they never knew. A surreal journey where memory and dreams collide ensues. Spanish with English subtitles.",Show description or single item,"[Movies, Foreign Language, Comedy, Quirky, Irreverent, Cheeky]",https://play-images-prod-ctf.tech.tvnz.co.nz/api/v1/web/image/4nxsgPQOg8l7hCWm19N3Em/943f3acd26e048b8da243416f589d18b/TheSoulOfFlies_coverimg-min.png.943f3acd26e048b8da243416f589d18b.jpg?width=1600&height=457,No duration found,No upload date found,WARNING: Deals with the issue of self-harming.,No content rating found
1,Dede,A young woman living in a remote mountain village defies her family and centuries of tradition when she falls in love with the wrong man. Georgian and Svan with English subtitles.,Show description or single item,"[Drama, Foreign Language, Movies, Revealing, All the Feels]",https://play-images-prod-ctf.tech.tvnz.co.nz/api/v1/web/image/6NUhOZWbKqsUOQEZtA8GNT/e10d3e7d6c0c899f2be1c3fd1605ac69/FilmStream_Dede_coverimg.png.e10d3e7d6c0c899f2be1c3fd1605ac69.jpg?width=1600&height=457,No duration found,No upload date found,No episode warnings found,No content rating found
2,The Unauthorised Melrose Place Story,"Discover the drama that went on behind the cameras of the 1990s hit series, Melrose Place, from the arrival of Heather Locklear to the actors begging writers for even wilder storylines to make them fan favourites.",Show description or single item,"[Movies, Drama, Nostalgic, All the Feels]",https://play-images-prod-ctf.tech.tvnz.co.nz/api/v1/web/image/2QvbGPbkWHTgeYXiQlBdz1/99f9ab2d29cd0717e92eda77361687eb/Lifetime_TheUnauthorizedMelrosePlaceStory_coverimg.png.99f9ab2d29cd0717e92eda77361687eb.jpg?width=1600&height=457,No duration found,No upload date found,No episode warnings found,No content rating found
3,Heaven,"In the first of V.C. Andrews' Casteel family series, the siblings are torn apart when their drunkard father sends them away one by one. Eldest daughter Heaven finds both torment and solace in her new home.",Show description or single item,"[Drama, Movies, All the Feels, Mysterious, Dark]",https://play-images-prod-ctf.tech.tvnz.co.nz/api/v1/web/image/7mm9dASBpuqmAXKJz6uwm/bc80576ace7555e67afb64967e369809/Lifetime_VCAndrewsHeaven_coverimg.png.bc80576ace7555e67afb64967e369809.jpg?width=1600&height=457,No duration found,No upload date found,No episode warnings found,No content rating found
4,Smoke & Mirrors,The true story of a man who fooled an entire country. The spy Francisco Paesa returns to Spain after being exiled and is determined to get his revenge against the Spanish government which betrayed him. Spanish with English subtitles.,Show description or single item,"[Drama, Foreign Language, Movies, Thrilling, Mysterious]",https://play-images-prod-ctf.tech.tvnz.co.nz/api/v1/web/image/3KGVMtEG5vtt27IXFF9gSb/9235fa6c16676cb5daeffaa69f9d1956/Filmstream_SmokeandMirrors_coverimg.png.9235fa6c16676cb5daeffaa69f9d1956.jpg?width=1600&height=457,No duration found,No upload date found,No episode warnings found,No content rating found

In [6]:
#cleaning
#deleting the square bracets 
df_movies_clean['tags']=df_movies_clean['tags'].astype(str).str.replace('[', '', regex = True)
df_movies_clean['tags']=df_movies_clean['tags'].astype(str).str.replace(']', '', regex = True)

In [7]:
#slove a problem in some movies name 
#some movies has in its name (,) comma which make confusion when adding multiple movies together in one list (it will consider the movie name as two movies)
#for the above reason we deleted all the commas from the movies names
df_movies_clean['title']=df_movies_clean['title'].astype(str).str.replace(",", '', regex = True)

In [8]:
#saving the data as CSV
df_movies_clean.to_csv(r'movies_data.csv',index=False)

In [6]:
#opening the csv file
df_movies= pd.read_csv('movies_data.csv', sep=',')
#df_movies.drop(['Unnamed: 0'], axis=1, inplace=True)  #in case we didn't use index=False when saveing as csv
df_movies.head()

#test
df_movies['description'][df_movies['title']=='Lady Chatterley\'s Lover']

98    After her husband is injured fighting in World War I, a beautiful young aristocrat embarks on a forbidden affair with a servant. Based on the novel by D. H. Lawrence.
Name: description, dtype: object

In [10]:
# determine the most used tags values counts to use them in the interest for the fake users
df_tags= df_movies.copy()
df_tags['tags'] = df_tags['tags'].str.split(', ')
df = df_tags.explode('tags')
tag_counts = df['tags'].value_counts()
tag_counts

'Movies'               152
'Drama'                113
'All the Feels'         52
'Foreign Language'      43
'Mysterious'            25
'Comedy'                23
'Local'                 23
'Thrilling'             22
'Revealing'             21
'Dark'                  19
'Romantic'              16
'Psychological'         15
'Epic'                  12
'Suspenseful'           12
'Thought-Provoking'     11
'Action-Packed'         10
'Quirky'                10
'Crack-Up'               8
'Provocative'            8
'Bold'                   7
'Irreverent'             7
'Lavish'                 6
'Witty'                  6
'Escapist'               5
'Cheeky'                 5
'Comforting'             5
'Kids'                   4
'Gritty'                 3
'Kiwi As'                3
'Nostalgic'              3
'Warm & Fuzzy'           3
'British Drama'          3
'Scary'                  2
'Investigative'          2
'Otherworldly'           2
'Charming'               1
'Sassy'                  1
'Naughty'                1
'Iconic'                 1
'Sport'                  1
'Silly'                  1
'Fast-Paced'             1
'Feel-Good'              1
Name: tags, dtype: int64

In [7]:
#generate fake users
fake = Faker() 
fake.seed_instance(0)
random.seed(0)

users = []

# Loop through user IDs from 0 to 99
for user_id in range(10000,10100):
    
    password=fake.password()

    # Generate user data
    age = fake.random_int(min=18, max=70)
    
    gender = fake.random_element(elements=("Male", "Female"))
    
    first_name=fake.first_name_male() if gender=="Male" else fake.first_name_female()
    
    interests = []
    for i in range(3):
        interest = fake.random_element(elements=("Action", "Comedy", "Drama", "Thrilling",'Mysterious', \
                                                 'Psychological','Romantic','Local','Epic','Kids'))
        if interest not in interests:                                        
            interests.append(interest)
        
    view_history = []
    for j in range(5):
        movie = random.choice(df_movies['title'])
        # add the title to the view_history if it is not already in the list
        if movie not in view_history:
            view_history.append(movie)
            
    email=fake.email()
    
    mother_language=fake.random_element(elements=("English","Māori","French", "Arabic", "Russian", "Chinese", "other"))
    
    
    # Create a new user dictionary and add the key-value pairs
    users_data = {}
    users_data["user_id"] = user_id
    users_data["first_name"]= first_name
    users_data["password"]= password
    users_data["age"] = age
    users_data["gender"] = gender
    users_data["interests"] = interests
    users_data["view_history"] = view_history
    users_data["email"]= email
    users_data["mother_language"]= mother_language
    
    # Append the user data dictionary to the users list
    users.append(users_data)
    
    
df_users = pd.DataFrame(users)
df_users.head()

,user_id,first_name,password,age,gender,interests,view_history,email,mother_language
0,10000,Eric,x6tnBEr4&i,63,Male,"[Comedy, Psychological, Local]","[Lady Chatterley's Lover, Happy End, Tasting Menu, Dangerous Matrimony, Last Chance for Christmas]",gomezleslie@example.net,Māori
1,10001,Robert,7(S7fOnb!q,32,Male,"[Drama, Epic, Local]","[Web of Dreams, Jim Henson's Turkey Hollow, Mood Indigo, Mistress Mercy, Mr Stein Goes Online]",millerluke@example.net,Arabic
2,10002,Andrew,eS4RjWVKW@,30,Male,"[Mysterious, Local, Comedy]","[Gone Mom: The Disappearance of Jennifer Dulos, Klown, Katy, A Love Yarn, Abducted: The Mary Stauffer Story]",sheltondavid@example.org,English
3,10003,Sarah,o@Q538nm8V,55,Female,"[Thrilling, Action, Mysterious]","[A Love Yarn, Blue is the Warmest Colour, The Unauthorised Beverly Hills 90210 Story, Seeds of Yesterday, Genghis]",thorntonnathan@example.org,French
4,10004,Larry,_D$Ut0z@Y&,25,Male,"[Thrilling, Drama, Comedy]","[Flowers in the Attic, I Was Lorena Bobbitt, The Most Magnificent Thing, P.S. I Love You, Kidnapped: The Hannah Anderson Story]",zclark@example.org,Chinese

In [8]:
#clean the data
#deleting the square bracets 
df_users['interests']=df_users['interests'].astype(str).str.replace('[', '', regex = True).str.replace(']', '', regex = True)
df_users['view_history']=df_users['view_history'].astype(str).str.replace('[', '', regex = True).str.replace(']', '', regex = True)

In [9]:
#deleting the ('') Quotation Mark from the values in the interest column, but we didn't do this for the values in the view_history column because
#some movies have (') Apostrophe in its name and we don't want to delete it, so we will clean this when preparing the data to the recommendation algorithem 
df_users['interests']=df_users['interests'].astype(str).str.replace("'", '', regex = True)

In [10]:
df_users.head() # this is the data frame that should be saved.

,user_id,first_name,password,age,gender,interests,view_history,email,mother_language
0,10000,Eric,x6tnBEr4&i,63,Male,"Comedy, Psychological, Local","""Lady Chatterley's Lover"", 'Happy End', 'Tasting Menu', 'Dangerous Matrimony', 'Last Chance for Christmas'",gomezleslie@example.net,Māori
1,10001,Robert,7(S7fOnb!q,32,Male,"Drama, Epic, Local","'Web of Dreams', ""Jim Henson's Turkey Hollow"", 'Mood Indigo', 'Mistress Mercy', 'Mr Stein Goes Online'",millerluke@example.net,Arabic
2,10002,Andrew,eS4RjWVKW@,30,Male,"Mysterious, Local, Comedy","'Gone Mom: The Disappearance of Jennifer Dulos', 'Klown', 'Katy', 'A Love Yarn', 'Abducted: The Mary Stauffer Story'",sheltondavid@example.org,English
3,10003,Sarah,o@Q538nm8V,55,Female,"Thrilling, Action, Mysterious","'A Love Yarn', 'Blue is the Warmest Colour', 'The Unauthorised Beverly Hills 90210 Story', 'Seeds of Yesterday', 'Genghis'",thorntonnathan@example.org,French
4,10004,Larry,_D$Ut0z@Y&,25,Male,"Thrilling, Drama, Comedy","'Flowers in the Attic', 'I Was Lorena Bobbitt', 'The Most Magnificent Thing', 'P.S. I Love You', 'Kidnapped: The Hannah Anderson Story'",zclark@example.org,Chinese

In [11]:
#save the data as csv
df_users.to_csv(r'fake_users_data.csv',index=False)

In [12]:
#opening the csv file
df_users_data= pd.read_csv('fake_users_data.csv', dtype={'user_id': 'str'},sep=',')  #dtype={'user_id': 'str'} we want the user_id to be read as a string for the interface
df_users_data.head(10)

,user_id,first_name,password,age,gender,interests,view_history,email,mother_language
0,10000,Eric,x6tnBEr4&i,63,Male,"Comedy, Psychological, Local","""Lady Chatterley's Lover"", 'Happy End', 'Tasting Menu', 'Dangerous Matrimony', 'Last Chance for Christmas'",gomezleslie@example.net,Māori
1,10001,Robert,7(S7fOnb!q,32,Male,"Drama, Epic, Local","'Web of Dreams', ""Jim Henson's Turkey Hollow"", 'Mood Indigo', 'Mistress Mercy', 'Mr Stein Goes Online'",millerluke@example.net,Arabic
2,10002,Andrew,eS4RjWVKW@,30,Male,"Mysterious, Local, Comedy","'Gone Mom: The Disappearance of Jennifer Dulos', 'Klown', 'Katy', 'A Love Yarn', 'Abducted: The Mary Stauffer Story'",sheltondavid@example.org,English
3,10003,Sarah,o@Q538nm8V,55,Female,"Thrilling, Action, Mysterious","'A Love Yarn', 'Blue is the Warmest Colour', 'The Unauthorised Beverly Hills 90210 Story', 'Seeds of Yesterday', 'Genghis'",thorntonnathan@example.org,French
4,10004,Larry,_D$Ut0z@Y&,25,Male,"Thrilling, Drama, Comedy","'Flowers in the Attic', 'I Was Lorena Bobbitt', 'The Most Magnificent Thing', 'P.S. I Love You', 'Kidnapped: The Hannah Anderson Story'",zclark@example.org,Chinese
5,10005,Michael,*74!8NPt*z,54,Male,"Thrilling, Action, Drama","'Britney Ever After', 'I Was Lorena Bobbitt', 'Divergent', ""A Sister's Nightmare"", 'The Orator'",matthewking@example.net,Arabic
6,10006,David,_2qtaAa+pL,35,Male,"Local, Psychological, Kids","'Le Grand Soir', 'Conan The Barbarian', 'Mistress Mercy', 'Return to Zero', 'A House on Fire'",emily99@example.org,Chinese
7,10007,David,%^Xd+4neb6,46,Male,"Drama, Local, Epic","'Dangerous Matrimony', 'Heart of a Lion', 'Mariposa', 'Heaven', ""Sione's 2: Unfinished Business""",modonnell@example.org,English
8,10008,William,*my5SJon)@,18,Male,"Epic, Kids, Comedy","'Splinters', 'The Soul of Flies', ""Manson's Lost Girls"", 'Secrets of Eden', 'The Assassin'",davidbanks@example.com,French
9,10009,Andrew,p+28Dpp)Qa,19,Male,"Mysterious, Epic, Psychological","'My Wedding and Other Secrets', 'Harry and Meghan: A Royal Romance', 'Shoplifters', 'Family Pictures', 'Gangsta Granny'",sheena09@example.net,Arabic

In [13]:
#test
df_users_data[df_users_data['user_id']=='10060']

,user_id,first_name,password,age,gender,interests,view_history,email,mother_language
60,10060,Dawn,aG2a2T(y!),26,Female,"Comedy, Kids, Epic","'Secrets of Eden', 'Trapped: The Alex Cooper Story', 'Toni Braxton: Unbreak My Heart', ""Sione's 2: Unfinished Business""",lori37@example.org,French

In [14]:
#the authentication function, that will check if the user's Id, name and password are valid
#we need it for the interface to login user 

def authenticate(user_id,username, password):
    
    #check the user_id
    ids= df_users_data['user_id'].tolist()
    #check that the name is related to the user_id
    names=df_users_data['first_name'][df_users_data['user_id']==user_id].iloc[0]
    #check that the password is related to the user_id
    passwords=df_users_data['password'][df_users_data['user_id']==user_id].iloc[0]
    
    if  user_id in ids and username == names  and password == passwords:
        #print('correct')
        return True
    else:
        #print('wrong')
        return False

In [15]:
authenticate('10004','Larry', '_D$Ut0z@Y&')

True